import Head from 'next/head';
import Menu from '../Menu';

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Menu />
        <main>
          {children}
        </main>
      </div>
    </>
  );
}

export default Layout;
